### ISSUE TITLE
Policy covering kaniko images

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/policy-catalog#11]
**What problem does the proposed policy solve? Please describe.**
Verify signatures for the kaniko project.

**What the proposed policy should do and the resources it will be applied to**
Check signatures

**What are the alternative solutions?**
N/A

**Additional context**
https://github.com/GoogleContainerTools/kaniko/issues/1761

**Comment by mattmoor** [comment]
We should get this onto the sigstore landscape as well.

**Comment by BobyMCbobs** [comment]
@mattmoor, I've made a PR here
https://github.com/chainguard-dev/policy-catalog/pull/18
